[workspace]
members = [
  "ntex",
  "ntex-codec",
  "ntex-macros",
  "ntex-router",
  "ntex-rt",
  "ntex-service",
  "ntex-web-macros",
]

[patch.crates-io]
ntex = { path = "ntex" }
ntex-rt = { path = "ntex-rt" }
ntex-codec = { path = "ntex-codec" }
ntex-router = { path = "ntex-router" }
ntex-service = { path = "ntex-service" }