[package]
name = "ntex-macros"
version = "0.1.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix runtime macros"
repository = "https://github.com/ntex-rs/ntex"
documentation = "https://docs.rs/ntex-macros/"
categories = ["network-programming", "asynchronous"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "^1"
syn = { version = "^1", features = ["full"] }

[dev-dependencies]
ntex-rt = { path = "../ntex-rt" }
